import { useEffect, useState, useRef } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { Loader2, Settings } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { Header } from "@/components/Header";
import { validateLocationFormat, normalizeLocationForApollo } from "@/utils/locationValidation";

const Configure = () => {
  const { user, loading: authLoading, requireAuth } = useAuth();
  const [searchParams] = useSearchParams();
  const courseId = searchParams.get('courseId');
  const autoGenerate = searchParams.get('autoGenerate') === 'true';
  const [courseData, setCourseData] = useState<any>(null);
  const [industries, setIndustries] = useState("");
  const [companies, setCompanies] = useState("");
  const [numTeams, setNumTeams] = useState("4");
  const [loading, setLoading] = useState(false);
  const [dataLoading, setDataLoading] = useState(true);
  const [polling, setPolling] = useState(false);
  const [generationRunId, setGenerationRunId] = useState<string | null>(null);
  const [projectsCompleted, setProjectsCompleted] = useState(0);
  const [totalProjects, setTotalProjects] = useState(0);
  const hasAutoGenerated = useRef(false);
  const pollingInterval = useRef<number | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    requireAuth();
  }, [authLoading]);

  useEffect(() => {
    if (!courseId) {
      toast.error("Course data not found. Please upload a syllabus first.");
      navigate("/upload");
      return;
    }

    const loadCourse = async () => {
      try {
        const { data, error } = await supabase
          .from('course_profiles')
          .select('*')
          .eq('id', courseId)
          .single();

        if (error) throw error;
        setCourseData(data);
      } catch (error) {
        console.error('Error loading course:', error);
        toast.error('Failed to load course data');
        navigate('/upload');
      } finally {
        setDataLoading(false);
      }
    };

    loadCourse();
  }, [courseId, navigate]);

  // Auto-generate if autoGenerate param is present (only once)
  useEffect(() => {
    if (autoGenerate && courseData && !dataLoading && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      console.log('Auto-generating projects with smart defaults...');
      // Trigger form submission after a brief moment to show the UI
      setTimeout(() => {
        const form = document.querySelector('form');
        if (form) {
          form.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }));
        }
      }, 500);
    }
  }, [autoGenerate, courseData, dataLoading]);

  // Polling effect - checks project generation status
  useEffect(() => {
    if (!polling || !generationRunId) return;

    const checkProjectStatus = async () => {
      try {
        const { data: projects, error } = await supabase
          .from('projects')
          .select('id, status')
          .eq('generation_run_id', generationRunId);

        if (error) {
          console.error('Polling error:', error);
          return;
        }

        const completed = projects?.filter(p => 
          p.status === 'ai_shell' || p.status === 'curated_live' || p.status === 'completed'
        ).length || 0;
        
        const total = projects?.length || 0;

        setProjectsCompleted(completed);
        setTotalProjects(total);

        // All projects are done
        if (total > 0 && completed === total) {
          if (pollingInterval.current) {
            clearInterval(pollingInterval.current);
            pollingInterval.current = null;
          }
          setPolling(false);
          
          const successCount = projects?.filter(p => 
            p.status === 'ai_shell' || p.status === 'curated_live'
          ).length || 0;
          
          toast.success(`${successCount} of ${total} projects generated successfully!`);
          navigate(`/projects?courseId=${courseId}`);
        }
      } catch (error) {
        console.error('Polling check error:', error);
      }
    };

    // Initial check
    checkProjectStatus();

    // Start polling every 10 seconds
    pollingInterval.current = window.setInterval(checkProjectStatus, 10000);

    // Cleanup on unmount
    return () => {
      if (pollingInterval.current) {
        clearInterval(pollingInterval.current);
        pollingInterval.current = null;
      }
    };
  }, [polling, generationRunId, courseId, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!courseId) {
      toast.error("Course data not found. Please upload a syllabus first.");
      navigate("/upload");
      return;
    }

    setLoading(true);

    try {
      // Step 1: Discover & enrich companies with market intelligence
      let generationRunId = null;

      // P0-2 FIX: Validate location format before passing to Apollo
      const locationForDiscovery = courseData?.search_location || courseData?.city_zip;

      if (locationForDiscovery) {
        // Validate location format
        const validation = validateLocationFormat(locationForDiscovery);

        if (!validation.isValid) {
          console.error('❌ Invalid location format:', validation.error);
          toast.error(`Invalid location format: ${validation.error}. Please re-configure your course.`, {
            duration: 5000
          });
          setLoading(false);
          return;
        }

        // Normalize for Apollo API
        const normalizedLocation = normalizeLocationForApollo(locationForDiscovery);

        if (!normalizedLocation) {
          console.error('❌ Location normalization failed');
          toast.error('Invalid location format. Please re-configure your course.', {
            duration: 5000
          });
          setLoading(false);
          return;
        }

        console.log('✅ Location validated for Apollo:', normalizedLocation);
        toast.info("Discovering partner companies...", { duration: 3000 });
        
        const { data: discoveryData, error: discoveryError } = await supabase.functions.invoke('discover-companies', {
          body: {
            courseId: courseId,
            location: normalizedLocation, // P0-2 FIX: Use validated Apollo-friendly format
            count: parseInt(numTeams)
          }
        });

        // Handle HTTP 500 errors (system failures)
        if (discoveryError) {
          console.error('Company discovery failed (HTTP 500):', discoveryError);
          toast.error("System error during company discovery. Please try again later or contact support.", { duration: 6000 });
          setLoading(false);
          return;
        }

        // Handle HTTP 200 with success:false (business failures or classified errors)
        if (discoveryData && !discoveryData.success) {
          const category = discoveryData.category || 'UNKNOWN_ERROR';
          const errorMessage = discoveryData.error || 'Discovery failed';
          const details = discoveryData.details || {};

          console.error('Company discovery failed (classified):', {
            category,
            message: errorMessage,
            details
          });

          // Show user-friendly message based on error category with diagnostics
          const diagnostics = discoveryData?.diagnostics;

          switch (category) {
            case 'DATA_ERROR':
              const diagnosticInfo = diagnostics
                ? ` Provider: ${diagnostics.primaryProvider}, Location: ${diagnostics.locationUsed || location}.` +
                  (diagnostics.usedFallback ? ` Fallback to ${diagnostics.fallbackProvider} was attempted but also returned 0 companies.` : '')
                : '';

              toast.error(
                `No suitable companies found for this course and location.${diagnosticInfo} ` +
                `Try adjusting the location to a nearby metro area or contact support if this persists.`,
                { duration: 8000 }
              );
              break;
            case 'CONFIG_ERROR':
              toast.error(
                "Service configuration error. Please contact support - this is not a user error.",
                { duration: 6000 }
              );
              break;
            case 'EXTERNAL_API_ERROR':
              const source = details.source || 'partner API';
              toast.error(
                `Our ${source} is temporarily unavailable. ` +
                (diagnostics?.usedFallback
                  ? `We attempted fallback to ${diagnostics.fallbackProvider} but it also failed. `
                  : '') +
                `Please try again in a few minutes or contact support.`,
                { duration: 8000 }
              );
              break;
            case 'DB_ERROR':
              toast.error(
                "Database error occurred. Please try again or contact support if the issue persists.",
                { duration: 6000 }
              );
              break;
            default:
              toast.error(
                errorMessage || "Company discovery failed. Please try again or contact support.",
                { duration: 6000 }
              );
          }

          setLoading(false);
          return;
        }

        // Success path
        generationRunId = discoveryData?.generation_run_id;
        const diagnostics = discoveryData?.diagnostics;

        console.log('✓ Company discovery complete. Generation run ID:', generationRunId);
        console.log('📊 Discovery diagnostics:', diagnostics);

        // Show detailed success message with provider info
        if (diagnostics?.usedFallback) {
          toast.success(
            `Found ${discoveryData?.count || 0} companies via ${diagnostics.fallbackProvider} (${diagnostics.primaryProvider} returned 0). ` +
            `Primary issue: ${diagnostics.primaryProviderError || 'Unknown'}`,
            { duration: 6000 }
          );
        } else {
          toast.success(`Found ${discoveryData?.count || 0} partner companies via ${diagnostics?.primaryProvider || 'discovery provider'}!`, { duration: 2000 });
        }
      }

      // Step 2: Generate projects using enriched company data
      toast.info("Generating projects with enriched data...", { duration: 3000 });
      const industriesArray = industries.split(',').map(i => i.trim()).filter(Boolean);
      const companiesArray = companies.split(',').map(c => c.trim()).filter(Boolean);

      const { data, error } = await supabase.functions.invoke('generate-projects', {
        body: {
          courseId,
          industries: industriesArray,
          companies: companiesArray,
          numTeams: parseInt(numTeams),
          generation_run_id: generationRunId // CRITICAL: Pass enriched data generation run ID
        }
      });

      if (error) {
        throw error;
      }

      // Generation started successfully - begin polling
      setGenerationRunId(data.generationRunId);
      setTotalProjects(parseInt(numTeams));
      setProjectsCompleted(0);
      setPolling(true);
      setLoading(false);
      
      toast.info("Project generation started. This may take a few minutes...", { duration: 3000 });
    } catch (error: any) {
      console.error('Generation error:', error);
      const errorMsg = error.message || "Failed to generate projects";
      if (errorMsg.includes('rate') || errorMsg.includes('429')) {
        toast.error("AI rate limit reached. Please wait 2-3 minutes and try again.", { duration: 6000 });
      } else {
        toast.error(errorMsg);
      }
    } finally {
      setLoading(false);
    }
  };

  if (authLoading || dataLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin text-primary mx-auto mb-4" />
          {autoGenerate && <p className="text-muted-foreground">Preparing smart project generation...</p>}
        </div>
      </div>
    );
  }

  if (loading && autoGenerate) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <div className="flex items-center justify-center h-[80vh]">
          <div className="text-center space-y-4 max-w-md">
            <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto" />
            <h2 className="text-2xl font-semibold">Generating Intelligent Matches</h2>
            <div className="space-y-2 text-sm text-muted-foreground">
              <p>✓ Analyzing course learning outcomes</p>
              <p>✓ Finding relevant companies in {courseData?.city_zip}</p>
              <p>✓ Matching companies to course objectives</p>
              <p className="text-xs mt-4">This may take 30-60 seconds...</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (polling) {
    const progress = totalProjects > 0 ? (projectsCompleted / totalProjects) * 100 : 0;
    
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <div className="flex items-center justify-center h-[80vh]">
          <div className="text-center space-y-6 max-w-md w-full px-4">
            <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto" />
            <h2 className="text-2xl font-semibold">Generating Projects</h2>
            <div className="space-y-4">
              <div className="space-y-2">
                <Progress value={progress} className="w-full" />
                <p className="text-sm text-muted-foreground">
                  {projectsCompleted} of {totalProjects} projects completed
                </p>
              </div>
              <div className="space-y-2 text-sm text-muted-foreground">
                <p>✓ Projects are being generated asynchronously</p>
                <p>✓ AI is analyzing and matching companies</p>
                <p>✓ This page will automatically refresh when complete</p>
                <p className="text-xs mt-4">This may take a few minutes...</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <div className="container mx-auto px-4 py-12 max-w-2xl">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold mb-2">Configure Project Generation</h1>
          <p className="text-muted-foreground">
            Customize industries, companies, and team settings
          </p>
        </div>

        {courseData && (
          <Card className="mb-6 bg-accent/50">
            <CardHeader>
              <CardTitle className="text-lg">Course Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <div><strong>Title:</strong> {courseData.title}</div>
              <div><strong>Duration:</strong> {courseData.weeks} weeks</div>
              <div><strong>Hours/Week:</strong> {courseData.hrs_per_week}</div>
              <div><strong>Learning Outcomes:</strong> {courseData.outcomes?.length || 0} identified</div>
            </CardContent>
          </Card>
        )}

        <Card className="shadow-[var(--shadow-card)]">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-secondary/10 rounded-lg flex items-center justify-center">
                <Settings className="h-6 w-6 text-secondary" />
              </div>
              <div>
                <CardTitle>Project Preferences</CardTitle>
                <CardDescription>
                  Specify your preferred industries and companies
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="industries">Industries</Label>
                <Input
                  id="industries"
                  placeholder="Healthcare, Finance, Technology, Energy"
                  value={industries}
                  onChange={(e) => setIndustries(e.target.value)}
                />
                <p className="text-sm text-muted-foreground">
                  Comma-separated list (optional). Leave blank for auto-detection.
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="companies">Specific Companies</Label>
                <Input
                  id="companies"
                  placeholder="Company A, Company B, Company C"
                  value={companies}
                  onChange={(e) => setCompanies(e.target.value)}
                />
                <p className="text-sm text-muted-foreground">
                  Comma-separated list (optional). Leave blank for industry-based generation.
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="numTeams">Number of Project Teams</Label>
                <Input
                  id="numTeams"
                  type="number"
                  min="1"
                  max="20"
                  value={numTeams}
                  onChange={(e) => setNumTeams(e.target.value)}
                />
                <p className="text-sm text-muted-foreground">
                  How many different projects to generate (1-20)
                </p>
              </div>

              <Button type="submit" className="w-full" disabled={loading}>
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Projects...
                  </>
                ) : (
                  "Generate Projects"
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Configure;
