-- Create a new ENUM type for our project statuses
CREATE TYPE project_status AS ENUM (
  'ai_shell',     -- The "draft" generated by the AI
  'curated_live', -- The "synced" project, approved by an Admin
  'in_progress',  -- A student has selected it
  'completed'     -- The project is finished
);

-- Add the new 'status' field to the projects table
ALTER TABLE public.projects
ADD COLUMN status project_status DEFAULT 'ai_shell';

-- Add the new 'description' field to the projects table
ALTER TABLE public.projects
ADD COLUMN description TEXT;

-- Add an index for the new status
CREATE INDEX idx_projects_status ON public.projects(status);