// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL ?? 'https://wnxjeldvzjubfgzvvzov.supabase.co';

const supabaseKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueGplbGR2emp1YmZnenZ2em92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzQ0NTYsImV4cCI6MjA3NzUxMDQ1Nn0.zE4zK-K5yYhuRlCDdpx5BSuacPoyZflAi_5Duiu8jY4';

// Optional: log presence of env overrides (no secrets)
console.debug('Supabase env presence (with safe fallbacks):', {
  hasUrlEnv: Boolean(import.meta.env.VITE_SUPABASE_URL),
  hasKeyEnv: Boolean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});